version: '3'

services:
  nginx-build-ubuntu22:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.ubuntu22
    volumes:
      - ./output/ubuntu22:/output
    environment:
      - DISABLE_LTO=1
      - NGINX_VERSION=1.26.3

  nginx-build-ubuntu24:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.ubuntu24
    volumes:
      - ./output/ubuntu24:/output
    environment:
      - DISABLE_LTO=1 
      - NGINX_VERSION=1.26.3